# Generated by Django 5.0.5 on 2024-09-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
