# Generated by Django 5.0.5 on 2024-09-24 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_data_delete_question"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Data",
        ),
    ]
