# Generated by Django 5.0.5 on 2024-09-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("polls", "0003_delete_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=200)),
                ("std", models.CharField(max_length=200)),
            ],
        ),
    ]
